#
# Asset copy
#


client_platform_path = meson.project_source_root() / 'Minecraft.Client/Platform'

install_subdir(meson.current_source_dir() / 'Common', install_dir : 'Common')
install_subdir(client_platform_path / 'Durango/Sound', install_dir : 'Durango')
install_subdir(client_platform_path / 'DurangoMedia/DLC', install_dir : 'Windows64Media') # Use this just for funsies so we get access to more dlc

#
# Asset build
#

# TODO: Need to make this take inputs
localisation = custom_target('Minecraft.Assets_Localisation',
  output : [ 'languages.loc', 'strings.h' ],
  command : [
    'python3', meson.project_source_root() / 'scripts/pack_loc.py',
     meson.current_source_dir() / 'Windows64Media/loc',
    '@OUTPUT0@',
    '@OUTPUT1@'
  ]
)

colour_table = custom_target('Minecraft.Assets_Colour_Table',
  output : 'HTMLColours.col',
  input : meson.current_source_dir() / 'Common/HTMLColours.xml',
  command : [
    'python3', meson.project_source_root() / 'scripts/build_col.py',
    '@INPUT@',
    '@OUTPUT@'
  ]
)

media_path = meson.current_source_dir() / 'Common/Media'

archive_sources = [ 
  localisation[0], # client_platform_path / 'Windows64Media/Media/languages.loc',
  colour_table,
  meson.current_source_dir() / 'Common/splashes.txt',
  meson.current_source_dir() / 'Common/Media/Graphics/SaveChest.png',
  meson.current_source_dir() / 'Common/Media/Graphics/MinecraftIcon.png',
  meson.current_source_dir() / 'Common/Media/Graphics/TexturePackIcon.png',
  meson.current_source_dir() / 'Windows64Media/Media/Tutorial.pck',
  meson.current_source_dir() / 'Windows64Media/Media/skinWin.swf',
  meson.current_source_dir() / 'Windows64Media/Media/skinHDWin.swf',
  meson.current_source_dir() / 'Windows64Media/Media/DLCOffersMenu480.swf',
  meson.current_source_dir() / 'Windows64Media/Media/DLCOffersMenu720.swf',
  meson.current_source_dir() / 'Windows64Media/Media/DLCOffersMenu1080.swf',
  meson.current_source_dir() / 'Windows64Media/Media/DLCOffersMenuVita.swf'
]
archive_sources_movies1080 = [
  media_path / 'skinHDGraphics.swf',
  media_path / 'skinHDGraphicsHud.swf',
  media_path / 'skinHDGraphicsLabels.swf',
  media_path / 'skinHDGraphicsInGame.swf',
  media_path / 'skinHD.swf',
  media_path / 'skinHDHud.swf',
  media_path / 'skinHDLabels.swf',
  media_path / 'skinHDInGame.swf',
  media_path / 'AnvilMenu1080.swf',
  media_path / 'BrewingStandMenu1080.swf',
  media_path / 'ChestMenu1080.swf',
  media_path / 'ChestLargeMenu1080.swf',
  media_path / 'ComponentLogo1080.swf',
  media_path / 'ComponentLogoSplit1080.swf',
  media_path / 'Controls1080.swf',
  media_path / 'ControlsRemotePlay1080.swf',
  media_path / 'CreateWorldMenu1080.swf',
  media_path / 'CreativeMenu1080.swf',
  media_path / 'Credits1080.swf',
  media_path / 'Crafting2x2Menu1080.swf',
  media_path / 'Crafting3x3Menu1080.swf',
  media_path / 'DeathMenu1080.swf',
  media_path / 'DebugCreateSchematic1080.swf',
  media_path / 'DebugMenu1080.swf',
  media_path / 'DebugOptionsMenu1080.swf',
  media_path / 'DebugSetCamera1080.swf',
  media_path / 'DebugUIConsoleComponent1080.swf',
  media_path / 'DebugUIMarketingGuide1080.swf',
  media_path / 'DLCMainMenu1080.swf',
  media_path / 'DispenserMenu1080.swf',
  media_path / 'EnchantingMenu1080.swf',
  media_path / 'EndPoem1080.swf',
  media_path / 'EULA1080.swf',
  media_path / 'FullscreenProgress1080.swf',
  media_path / 'FurnaceMenu1080.swf',
  media_path / 'HelpAndOptionsMenu1080.swf',
  media_path / 'HowToPlay1080.swf',
  media_path / 'HowToPlayMenu1080.swf',
  media_path / 'HUD1080.swf',
  media_path / 'InGameHostOptions1080.swf',
  media_path / 'InGameInfoMenu1080.swf',
  media_path / 'InGamePlayerOptions1080.swf',
  media_path / 'InGameTeleportMenu1080.swf',
  media_path / 'Intro1080.swf',
  media_path / 'InventoryMenu1080.swf',
  media_path / 'JoinMenu1080.swf',
  media_path / 'LoadOrJoinMenu1080.swf',
  media_path / 'LaunchMoreOptionsMenu1080.swf',
  media_path / 'LeaderboardMenu1080.swf',
  media_path / 'LoadMenu1080.swf',
  media_path / 'MainMenu1080.swf',
  media_path / 'MenuBackground1080.swf',
  media_path / 'MessageBox1080.swf',
  media_path / 'NewUpdateMessage1080.swf',
  media_path / 'Panorama1080.swf',
  media_path / 'PauseMenu1080.swf',
  media_path / 'PressStartToPlay1080.swf',
  media_path / 'QuadrantSignin1080.swf',
  media_path / 'ReinstallMenu1080.swf',
  media_path / 'SaveMenu1080.swf',
  media_path / 'SaveMessage1080.swf',
  media_path / 'SettingsMenu1080.swf',
  media_path / 'SettingsAudioMenu1080.swf',
  media_path / 'SettingsControlMenu1080.swf',
  media_path / 'SettingsGraphicsMenu1080.swf',
  media_path / 'SettingsOptionsMenu1080.swf',
  media_path / 'SettingsUIMenu1080.swf',
  media_path / 'SignEntryMenu1080.swf',
  media_path / 'SkinSelectMenu1080.swf',
  media_path / 'Timer1080.swf',
  media_path / 'ToolTips1080.swf',
  media_path / 'TradingMenu1080.swf',
  media_path / 'TutorialPopup1080.swf',
  media_path / 'AnvilMenuSplit1080.swf',
  media_path / 'BrewingStandMenuSplit1080.swf',
  media_path / 'ChestMenuSplit1080.swf',
  media_path / 'ChestLargeMenuSplit1080.swf',
  media_path / 'ControlsSplit1080.swf',
  media_path / 'Crafting2x2MenuSplit1080.swf',
  media_path / 'Crafting3x3MenuSplit1080.swf',
  media_path / 'CreativeMenuSplit1080.swf',
  media_path / 'DeathMenuSplit1080.swf',
  media_path / 'DispenserMenuSplit1080.swf',
  media_path / 'EnchantingMenuSplit1080.swf',
  media_path / 'FurnaceMenuSplit1080.swf',
  media_path / 'FullscreenProgressSplit1080.swf',
  media_path / 'HelpAndOptionsMenuSplit1080.swf',
  media_path / 'HowToPlaySplit1080.swf',
  media_path / 'HowToPlayMenuSplit1080.swf',
  media_path / 'HUDSplit1080.swf',
  media_path / 'InGameHostOptionsSplit1080.swf',
  media_path / 'InGameInfoMenuSplit1080.swf',
  media_path / 'InGameTeleportMenuSplit1080.swf',
  media_path / 'InGamePlayerOptionsSplit1080.swf',
  media_path / 'InventoryMenuSplit1080.swf',
  media_path / 'MessageBoxSplit1080.swf',
  media_path / 'PanoramaSplit1080.swf',
  media_path / 'PauseMenuSplit1080.swf',
  media_path / 'ReinstallMenuSplit1080.swf',
  media_path / 'SettingsAudioMenuSplit1080.swf',
  media_path / 'SettingsControlMenuSplit1080.swf',
  media_path / 'SettingsGraphicsMenuSplit1080.swf',
  media_path / 'SettingsMenuSplit1080.swf',
  media_path / 'SettingsOptionsMenuSplit1080.swf',
  media_path / 'SettingsUIMenuSplit1080.swf',
  media_path / 'SignEntryMenuSplit1080.swf',
  media_path / 'SkinSelectMenuSplit1080.swf',
  media_path / 'TimerSplit1080.swf',
  media_path / 'ToolTipsSplit1080.swf',
  media_path / 'TradingMenuSplit1080.swf',
  media_path / 'TutorialPopupSplit1080.swf',
  media_path / 'Keyboard1080.swf',
  media_path / 'KeyboardSplit1080.swf'
]
archive_sources_movies720 = [
  media_path / 'skinGraphics.swf',
  media_path / 'skinGraphicsHud.swf',
  media_path / 'skinGraphicsLabels.swf',
  media_path / 'skinGraphicsInGame.swf',
  media_path / 'skin.swf',
  media_path / 'skinHud.swf',
  media_path / 'skinLabels.swf',
  media_path / 'skinInGame.swf',
  media_path / 'AnvilMenu720.swf',
  media_path / 'BrewingStandMenu720.swf',
  media_path / 'ChestMenu720.swf',
  media_path / 'ChestLargeMenu720.swf',
  media_path / 'ComponentLogo720.swf',
  media_path / 'Controls720.swf',
  media_path / 'CreateWorldMenu720.swf',
  media_path / 'CreativeMenu720.swf',
  media_path / 'Credits720.swf',
  media_path / 'Crafting2x2Menu720.swf',
  media_path / 'Crafting3x3Menu720.swf',
  media_path / 'DeathMenu720.swf',
  media_path / 'DebugCreateSchematic720.swf',
  media_path / 'DebugMenu720.swf',
  media_path / 'DebugOptionsMenu720.swf',
  media_path / 'DebugSetCamera720.swf',
  media_path / 'DebugUIConsoleComponent720.swf',
  media_path / 'DebugUIMarketingGuide720.swf',
  media_path / 'DLCMainMenu720.swf',
  media_path / 'DispenserMenu720.swf',
  media_path / 'EnchantingMenu720.swf',
  media_path / 'EndPoem720.swf',
  media_path / 'EULA720.swf',
  media_path / 'FullscreenProgress720.swf',
  media_path / 'FurnaceMenu720.swf',
  media_path / 'HelpAndOptionsMenu720.swf',
  media_path / 'HowToPlay720.swf',
  media_path / 'HowToPlayMenu720.swf',
  media_path / 'HUD720.swf',
  media_path / 'InGameHostOptions720.swf',
  media_path / 'InGameInfoMenu720.swf',
  media_path / 'InGamePlayerOptions720.swf',
  media_path / 'InGameTeleportMenu720.swf',
  media_path / 'Intro720.swf',
  media_path / 'InventoryMenu720.swf',
  media_path / 'JoinMenu720.swf',
  media_path / 'LoadOrJoinMenu720.swf',
  media_path / 'LaunchMoreOptionsMenu720.swf',
  media_path / 'LeaderboardMenu720.swf',
  media_path / 'LoadMenu720.swf',
  media_path / 'MainMenu720.swf',
  media_path / 'MenuBackground720.swf',
  media_path / 'MessageBox720.swf',
  media_path / 'NewUpdateMessage720.swf',
  media_path / 'Panorama720.swf',
  media_path / 'PauseMenu720.swf',
  media_path / 'PressStartToPlay720.swf',
  media_path / 'QuadrantSignin720.swf',
  media_path / 'ReinstallMenu720.swf',
  media_path / 'SaveMessage720.swf',
  media_path / 'SettingsMenu720.swf',
  media_path / 'SettingsAudioMenu720.swf',
  media_path / 'SettingsControlMenu720.swf',
  media_path / 'SettingsGraphicsMenu720.swf',
  media_path / 'SettingsOptionsMenu720.swf',
  media_path / 'SettingsUIMenu720.swf',
  media_path / 'SignEntryMenu720.swf',
  media_path / 'SkinSelectMenu720.swf',
  media_path / 'Timer720.swf',
  media_path / 'ToolTips720.swf',
  media_path / 'TradingMenu720.swf',
  media_path / 'TutorialPopup720.swf',
  media_path / 'AnvilMenuSplit720.swf',
  media_path / 'BrewingStandMenuSplit720.swf',
  media_path / 'ChestMenuSplit720.swf',
  media_path / 'ChestLargeMenuSplit720.swf',
  media_path / 'ControlsSplit720.swf',
  media_path / 'ComponentLogoSplit720.swf',
  media_path / 'Crafting2x2MenuSplit720.swf',
  media_path / 'Crafting3x3MenuSplit720.swf',
  media_path / 'CreativeMenuSplit720.swf',
  media_path / 'DeathMenuSplit720.swf',
  media_path / 'DispenserMenuSplit720.swf',
  media_path / 'EnchantingMenuSplit720.swf',
  media_path / 'FurnaceMenuSplit720.swf',
  media_path / 'FullscreenProgressSplit720.swf',
  media_path / 'GamertagSplit720.swf',
  media_path / 'HelpAndOptionsMenuSplit720.swf',
  media_path / 'HowToPlaySplit720.swf',
  media_path / 'HowToPlayMenuSplit720.swf',
  media_path / 'HUDSplit720.swf',
  media_path / 'InGameHostOptionsSplit720.swf',
  media_path / 'InGameInfoMenuSplit720.swf',
  media_path / 'InGamePlayerOptionsSplit720.swf',
  media_path / 'InventoryMenuSplit720.swf',
  media_path / 'MessageBoxSplit720.swf',
  media_path / 'PanoramaSplit720.swf',
  media_path / 'PauseMenuSplit720.swf',
  media_path / 'ReinstallMenuSplit720.swf',
  media_path / 'SettingsAudioMenuSplit720.swf',
  media_path / 'SettingsControlMenuSplit720.swf',
  media_path / 'SettingsGraphicsMenuSplit720.swf',
  media_path / 'SettingsMenuSplit720.swf',
  media_path / 'SettingsOptionsMenuSplit720.swf',
  media_path / 'SettingsUIMenuSplit720.swf',
  media_path / 'SignEntryMenuSplit720.swf',
  media_path / 'InGameTeleportMenuSplit720.swf',
  media_path / 'ToolTipsSplit720.swf',
  media_path / 'TradingMenuSplit720.swf',
  media_path / 'TrialExitUpsell720.swf',
  media_path / 'TutorialPopupSplit720.swf',
  media_path / 'SkinSelectMenuSplit720.swf'
]
archive_sources_movies480 = [
  media_path / 'AnvilMenu480.swf',
  media_path / 'BrewingStandMenu480.swf',
  media_path / 'ChestLargeMenu480.swf',
  media_path / 'ChestMenu480.swf',
  media_path / 'Controls480.swf',
  media_path / 'ComponentLogo480.swf',
  media_path / 'Crafting2x2Menu480.swf',
  media_path / 'Crafting3x3Menu480.swf',
  media_path / 'CreateWorldMenu480.swf',
  media_path / 'CreativeMenu480.swf',
  media_path / 'Credits480.swf',
  media_path / 'DeathMenu480.swf',
  media_path / 'DispenserMenu480.swf',
  media_path / 'DLCMainMenu480.swf',
  media_path / 'EnchantingMenu480.swf',
  media_path / 'EndPoem480.swf',
  media_path / 'EULA480.swf',
  media_path / 'FullscreenProgress480.swf',
  media_path / 'FurnaceMenu480.swf',
  media_path / 'HelpAndOptionsMenu480.swf',
  media_path / 'HowToPlay480.swf',
  media_path / 'HowToPlayMenu480.swf',
  media_path / 'HUD480.swf',
  media_path / 'InGameHostOptions480.swf',
  media_path / 'InGameInfoMenu480.swf',
  media_path / 'InGamePlayerOptions480.swf',
  media_path / 'Intro480.swf',
  media_path / 'InventoryMenu480.swf',
  media_path / 'JoinMenu480.swf',
  media_path / 'LaunchMoreOptionsMenu480.swf',
  media_path / 'LeaderboardMenu480.swf',
  media_path / 'LoadMenu480.swf',
  media_path / 'LoadOrJoinMenu480.swf',
  media_path / 'MainMenu480.swf',
  media_path / 'MenuBackground480.swf',
  media_path / 'MessageBox480.swf',
  media_path / 'NewUpdateMessage480.swf',
  media_path / 'Panorama480.swf',
  media_path / 'PauseMenu480.swf',
  media_path / 'PressStartToPlay480.swf',
  media_path / 'ReinstallMenu480.swf',
  media_path / 'SaveMessage480.swf',
  media_path / 'SettingsAudioMenu480.swf',
  media_path / 'SettingsControlMenu480.swf',
  media_path / 'SettingsGraphicsMenu480.swf',
  media_path / 'SettingsMenu480.swf',
  media_path / 'SettingsOptionsMenu480.swf',
  media_path / 'SettingsUIMenu480.swf',
  media_path / 'SignEntryMenu480.swf',
  media_path / 'SkinSelectMenu480.swf',
  media_path / 'InGameTeleportMenu480.swf',
  media_path / 'Timer480.swf',
  media_path / 'ToolTips480.swf',
  media_path / 'TradingMenu480.swf',
  media_path / 'TrialExitUpsell480.swf',
  media_path / 'TutorialPopup480.swf'
]
archive_sources_moviesVita = [
  media_path / 'skinGraphics.swf',
  media_path / 'skinGraphicsHud.swf',
  media_path / 'skinGraphicsLabels.swf',
  media_path / 'skinGraphicsInGame.swf',
  media_path / 'skin.swf',
  media_path / 'skinHud.swf',
  media_path / 'skinLabels.swf',
  media_path / 'skinInGame.swf',
  media_path / 'AnvilMenuVita.swf',
  media_path / 'BrewingStandMenuVita.swf',
  media_path / 'ChestLargeMenuVita.swf',
  media_path / 'ChestMenuVita.swf',
  media_path / 'ComponentLogoVita.swf',
  media_path / 'ControlsVita.swf',
  media_path / 'ControlsTVVita.swf',
  media_path / 'Crafting2x2MenuVita.swf',
  media_path / 'Crafting3x3MenuVita.swf',
  media_path / 'CreateWorldMenuVita.swf',
  media_path / 'CreativeMenuVita.swf',
  media_path / 'CreditsVita.swf',
  media_path / 'DeathMenuVita.swf',
  media_path / 'DispenserMenuVita.swf',
  media_path / 'DLCMainMenuVita.swf',
  media_path / 'EnchantingMenuVita.swf',
  media_path / 'EndPoemVita.swf',
  media_path / 'EULAVita.swf',
  media_path / 'FullscreenProgressVita.swf',
  media_path / 'FurnaceMenuVita.swf',
  media_path / 'HelpAndOptionsMenuVita.swf',
  media_path / 'HowToPlayMenuVita.swf',
  media_path / 'HowToPlayVita.swf',
  media_path / 'HUDVita.swf',
  media_path / 'InGameHostOptionsVita.swf',
  media_path / 'InGameInfoMenuVita.swf',
  media_path / 'InGamePlayerOptionsVita.swf',
  media_path / 'InGameTeleportMenuVita.swf',
  media_path / 'IntroVita.swf',
  media_path / 'InventoryMenuVita.swf',
  media_path / 'JoinMenuVita.swf',
  media_path / 'LaunchMoreOptionsMenuVita.swf',
  media_path / 'LeaderboardMenuVita.swf',
  media_path / 'LoadMenuVita.swf',
  media_path / 'LoadOrJoinMenuVita.swf',
  media_path / 'MainMenuVita.swf',
  media_path / 'MenuBackgroundVita.swf',
  media_path / 'MessageBoxVita.swf',
  media_path / 'NewUpdateMessageVita.swf',
  media_path / 'PanoramaVita.swf',
  media_path / 'PauseMenuVita.swf',
  media_path / 'PressStartToPlayVita.swf',
  media_path / 'ReinstallMenuVita.swf',
  media_path / 'SaveMessageVita.swf',
  media_path / 'SettingsAudioMenuVita.swf',
  media_path / 'SettingsControlMenuVita.swf',
  media_path / 'SettingsGraphicsMenuVita.swf',
  media_path / 'SettingsMenuVita.swf',
  media_path / 'SettingsOptionsMenuVita.swf',
  media_path / 'SettingsUIMenuVita.swf',
  media_path / 'SignEntryMenuVita.swf',
  media_path / 'SkinSelectMenuVita.swf',
  media_path / 'TimerVita.swf',
  media_path / 'ToolTipsVita.swf',
  media_path / 'TradingMenuVita.swf',
  media_path / 'TutorialPopupVita.swf',
  media_path / 'DebugCreateSchematic720.swf',
  media_path / 'DebugMenu720.swf',
  media_path / 'DebugOptionsMenu720.swf',
  media_path / 'DebugSetCamera720.swf',
  media_path / 'DebugUIConsoleComponent720.swf',
  media_path / 'DebugUIMarketingGuide720.swf'
]

assets_archive = custom_target('Minecraft.Assets_Archive',
  output : 'MediaWindows64.arc',
  input : archive_sources + archive_sources_movies1080 + archive_sources_movies720,
  command : [
    'python3', meson.project_source_root() / 'scripts/pack_arc.py',
    '@OUTPUT@',
    '@INPUT@'
  ],
  install : true,
  install_dir : 'Common/Media',
  # build_subdir : 'Common/Media',
  build_by_default : true
)

#
# Dep defines
#

assets_localisation_dep = declare_dependency(
    sources : localisation[1],
    # sources : client_platform_path / 'Windows64Media/strings.h', 
    include_directories : include_directories('.')
)

